#!/bin/bash

# MongoDB Atlas Setup Script
# This script helps you understand what to do in MongoDB Atlas

echo "========================================="
echo "MONGODB ATLAS SETUP GUIDE"
echo "========================================="
echo ""
echo "STEP 1: Create MongoDB Atlas Account (if you don't have one)"
echo "  - Go to: https://www.mongodb.com/cloud/atlas/register"
echo "  - Sign up for FREE"
echo "  - Verify your email"
echo ""
echo "STEP 2: Create a New Cluster"
echo "  - Click 'Build a Database'"
echo "  - Choose 'M0 Sandbox' (FREE Forever)"
echo "  - Select your region (closest to you)"
echo "  - Click 'Create'"
echo ""
echo "STEP 3: Create Database User"
echo "  - Security Quickstart will appear"
echo "  - Choose 'Username and Password'"
echo "  - Username: janproject_user"
echo "  - Password: (auto-generated or create your own)"
echo "  - SAVE THE PASSWORD - You'll need it!"
echo "  - Click 'Create User'"
echo ""
echo "STEP 4: Add Your IP Address"
echo "  - Click 'Add My Current IP Address'"
echo "  - OR click 'Allow Access from Anywhere' (0.0.0.0/0)"
echo "  - Click 'Finish and Close'"
echo ""
echo "STEP 5: Get Connection String"
echo "  - Click 'Connect' on your cluster"
echo "  - Click 'Drivers'"
echo "  - Copy the connection string"
echo "  - It looks like:"
echo "    mongodb+srv://janproject_user:<password>@cluster0.xxxxx.mongodb.net/"
echo ""
echo "STEP 6: Update .env File"
echo "  - Open: backend/.env"
echo "  - Find: MONGODB_URI="
echo "  - Paste your connection string"
echo "  - Replace <password> with your actual password"
echo "  - Add database name at the end: /janproject"
echo ""
echo "Example:"
echo "MONGODB_URI=mongodb+srv://janproject_user:MyPass123@cluster0.xxxxx.mongodb.net/janproject?retryWrites=true&w=majority"
echo ""
echo "========================================="
echo "After updating .env, restart your server:"
echo "  cd backend"
echo "  npm run dev"
echo "========================================="
